kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: 4.07.1.bench
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - eval $(opam env)
  - opam install dune.1.11.4
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - make ocaml-versions/4.07.1.bench
