kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: 4.07.1.bench
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - eval $(opam env)
  - opam install dune
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - make ocaml-versions/4.07.1.bench
- name: 4.07.1.parallelbench
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - eval $(opam env)
  - opam install dune
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - export BENCH_TARGET=parallelbench
  - make ocaml-versions/4.07.1.bench
- name: 4.06.1+multicore.multibench
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - eval $(opam env)
  - opam install dune
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - export BENCH_TARGET=multibench
  - make ocaml-versions/4.06.1+multicore.bench
