#!/bin/bash

export OCAML_INSTR_FILE=instrlog
#O=1000000 disables compaction, a=2 is best-fit policy
export OCAMLRUNPARAM="O=1000000,a=2"
OUTFILE=$1
shift
eval $@
python3 $OPAM_SWITCH_PREFIX/bin/process_instrlog.py $OUTFILE instrlog > $OUTFILE
rm instrlog
