#!/bin/bash

export OCAML_EVENTLOG_ENABLED="1"
OUTFILE=$1
BENCH_NAME=$(basename $OUTFILE .pausetimes_multicore.bench)
shift
eval $@
ocaml-eventlog-pausetimes *.eventlog $BENCH_NAME > $OUTFILE
rm *.eventlog
