#!/bin/bash

export OCAML_EVENTLOG_ENABLED="1"
OUTFILE=$1
BENCH_NAME=$(basename $OUTFILE .pausetimes_trunk.bench)
shift
eval $@
echo $BENCH_NAME
echo $OUTFILE
if ls *.eventlog 1> /dev/null 2>&1; then
    ocaml-eventlog-pausetimes *.eventlog $BENCH_NAME > $OUTFILE
    rm *.eventlog
fi
