#!/bin/bash

export OCAML_INSTR_FILE=instrlog
#O=1000000 disables compaction, a=1 is first-fit policy
#export OCAMLRUNPARAM="O=1000000,a=1"
OUTFILE=$1
shift
eval $@
python3 $OPAM_SWITCH_PREFIX/bin/process_instrlog.py $OUTFILE instrlog > $OUTFILE
rm instrlog
