#!/bin/bash

TMP=$(mktemp)
OUTFILE=$1
BENCH_NAME=$(basename $OUTFILE .pausetimes_multicore.bench)
shift
eval "olly latency -o $TMP --json '$@'"
cat $TMP | jq "{name: \"$BENCH_NAME\"} + ." >$OUTFILE
rm $TMP
